language: node_js

node_js: 
    - '11'

cache:
  directories:
    - node_modules

install:
  - npm install

before_script:

script:
  - npm run test

branches:
  only:
    - master
